language: cpp

sudo: false
dist: trusty

cache:
  directories:
    - ${TRAVIS_BUILD_DIR}/deps

addons:
  - &gcc-5 { apt: { sources: [ 'ubuntu-toolchain-r-test' ], packages: [ 'g++-5', 'libstdc++-5-dev', 'language-pack-tr' ] } }
  - &gcc-6 { apt: { sources: [ 'ubuntu-toolchain-r-test' ], packages: [ 'g++-6', 'libstdc++-6-dev', 'language-pack-tr' ] } }
  - &gcc-7 { apt: { sources: [ 'ubuntu-toolchain-r-test' ], packages: [ 'g++-7', 'libstdc++-7-dev', 'language-pack-tr' ] } }
  - &clang-5_0 { apt: { sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-5.0' ], packages: [ 'clang-5.0', 'libstdc++-5-dev', 'language-pack-tr' ] } }
  - &clang-6_0 { apt: { sources: [ 'ubuntu-toolchain-r-test', 'llvm-toolchain-trusty-6.0' ], packages: [ 'clang-6.0', 'libstdc++-5-dev', 'language-pack-tr' ] } }

env:
  global:
    - BOOST_VERSION=1.67.0

matrix:
  fast_finish: true

  include:
    - { os: linux, addons: *gcc-6, env: TRAVIS_CC=gcc-6 TRAVIS_CXX=g++-6 VARIANT=debug LINK=static }
    - { os: linux, addons: *gcc-6, env: TRAVIS_CC=gcc-6 TRAVIS_CXX=g++-6 VARIANT=debug LINK=shared }
    - { os: linux, addons: *gcc-6, env: TRAVIS_CC=gcc-6 TRAVIS_CXX=g++-6 VARIANT=release LINK=static }
    - { os: linux, addons: *gcc-6, env: TRAVIS_CC=gcc-6 TRAVIS_CXX=g++-6 VARIANT=release LINK=shared }

    - { os: linux, addons: *gcc-7, env: TRAVIS_CC=gcc-7 TRAVIS_CXX=g++-7 VARIANT=debug LINK=static }
    - { os: linux, addons: *gcc-7, env: TRAVIS_CC=gcc-7 TRAVIS_CXX=g++-7 VARIANT=debug LINK=shared }
    - { os: linux, addons: *gcc-7, env: TRAVIS_CC=gcc-7 TRAVIS_CXX=g++-7 VARIANT=release LINK=static }
    - { os: linux, addons: *gcc-7, env: TRAVIS_CC=gcc-7 TRAVIS_CXX=g++-7 VARIANT=release LINK=shared }

    - { os: linux, addons: *clang-5_0, env: TRAVIS_CC=clang-5.0 TRAVIS_CXX=clang++-5.0 VARIANT=debug LINK=static }
    - { os: linux, addons: *clang-5_0, env: TRAVIS_CC=clang-5.0 TRAVIS_CXX=clang++-5.0 VARIANT=debug LINK=shared }
    - { os: linux, addons: *clang-5_0, env: TRAVIS_CC=clang-5.0 TRAVIS_CXX=clang++-5.0 VARIANT=release LINK=static }
    - { os: linux, addons: *clang-5_0, env: TRAVIS_CC=clang-5.0 TRAVIS_CXX=clang++-5.0 VARIANT=release LINK=shared }

    - { os: linux, addons: *clang-6_0, env: TRAVIS_CC=clang-6.0 TRAVIS_CXX=clang++-6.0 VARIANT=debug LINK=static }
    - { os: linux, addons: *clang-6_0, env: TRAVIS_CC=clang-6.0 TRAVIS_CXX=clang++-6.0 VARIANT=debug LINK=shared }
    - { os: linux, addons: *clang-6_0, env: TRAVIS_CC=clang-6.0 TRAVIS_CXX=clang++-6.0 VARIANT=release LINK=static }
    - { os: linux, addons: *clang-6_0, env: TRAVIS_CC=clang-6.0 TRAVIS_CXX=clang++-6.0 VARIANT=release LINK=shared }

    - { os: linux, addons: *gcc-5, env: TRAVIS_CC=gcc-5 TRAVIS_CXX=g++-5 VARIANT=coverage LINK=static }

install:
  - /bin/sh -e .travis.sh install

script:
  - /bin/sh -e .travis.sh build
