language: cpp

compiler:
  - gcc
  - clang

os:
  - linux

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: always

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

  - wget http://sourceforge.net/projects/boost/files/boost/1.58.0/boost_1_58_0.tar.bz2/download -O boost_1_58_0.tar.bz2
  - tar jxf boost_1_58_0.tar.bz2
  - export BOOST_ROOT=$PWD/boost_1_58_0

script:
  - /bin/sh -e ./build.sh /missio/lib variant=debug toolset=$CC
  - /bin/sh -e ./build.sh /missio/test variant=debug toolset=$CC
