language: cpp

sudo: required

compiler:
  - gcc
  - clang

os:
  - linux

notifications:
  email:
    on_success: change
    on_failure: always
    on_start: always

env:
  matrix:
    - BUILD_VARIANT=debug   BUILD_ADDRESS_MODEL=32
    - BUILD_VARIANT=release BUILD_ADDRESS_MODEL=32
    - BUILD_VARIANT=debug   BUILD_ADDRESS_MODEL=64
    - BUILD_VARIANT=release BUILD_ADDRESS_MODEL=64

before_install:
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq

install:
  - sudo apt-get install -qq gcc-4.8 g++-4.8 libstdc++-4.8-dev libboost-all-dev
  - sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-4.8 40 --slave /usr/bin/g++ g++ /usr/bin/g++-4.8

script:
  - /bin/sh -e ./build/unix/build.sh toolset=${CC} boost=system variant=${BUILD_VARIANT} address-model=${BUILD_ADDRESS_MODEL}
