language: cpp

sudo: false

packages:
  - &boost [ 'libboost1.55-dev', 'libboost1.55-tools-dev', 'libboost-system1.55-dev', 'libboost-date-time1.55-dev', 'libboost-filesystem1.55-dev' ]

addons:
  - &gcc-5 { apt: { sources: [ 'ubuntu-toolchain-r-test', 'boost-latest' ], packages: [ *boost, 'g++-5' ] } }
  - &clang-3_7 { apt: { sources: [ 'ubuntu-toolchain-r-test', 'boost-latest', 'llvm-toolchain-precise-3.7' ], packages: [ *boost, 'clang-3.7' ] } }

matrix:
  include:
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=debug LINK=static }
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=debug LINK=shared }
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=release LINK=static }
    - { os: linux, compiler: gcc, addons: *gcc-5, env: TOOLSET=gcc-5 VARIANT=release LINK=shared }

#    - { os: linux, compiler: clang, addons: *clang-3_7, env: TOOLSET=clang-3.7 VARIANT=debug LINK=static }
#    - { os: linux, compiler: clang, addons: *clang-3_7, env: TOOLSET=clang-3.7 VARIANT=debug LINK=shared }
#    - { os: linux, compiler: clang, addons: *clang-3_7, env: TOOLSET=clang-3.7 VARIANT=release LINK=static }
#    - { os: linux, compiler: clang, addons: *clang-3_7, env: TOOLSET=clang-3.7 VARIANT=release LINK=shared }

    - os: linux
      compiler: gcc
      addons: *gcc-5
      env: TOOLSET=gcc-5 VARIANT=coverage LINK=static
      before_script: pip install --user cpp-coveralls
      after_success: coveralls --gcov gcov-5 --gcov-options '\-lp' --exclude test --exclude perf

script: /bin/sh -e ./build/unix/build.sh toolset=${TOOLSET} link=${LINK} boost=system boost-link=${LINK} variant=${VARIANT}
