version: "{build}"

os: Visual Studio 2015

platform: x64

clone_folder: c:\projects\missio

environment:
  BOOST_ROOT: c:\Libraries\boost_1_60_0

  matrix:
    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: debug
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: release
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: debug
      BUILD_LINK: static

    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: release
      BUILD_LINK: static

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: debug
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: release
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: debug
      BUILD_LINK: static

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: release
      BUILD_LINK: static

build_script:
  - build/win/build.bat toolset=msvc link=%BUILD_LINK% boost=source boost-link=%BUILD_LINK% variant=%BUILD_VARIANT% address-model=%BUILD_ADDRESS_MODEL%
