version: "{build}"

os: Visual Studio 2015

platform: x64

skip_tags: true

clone_folder: c:\projects\missio

environment:
  BOOST_ROOT: C:\Libraries\boost_1_63_0

  matrix:
    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: debug
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: release
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: debug
      BUILD_LINK: static

    - BUILD_ADDRESS_MODEL: 32
      BUILD_VARIANT: release
      BUILD_LINK: static

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: debug
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: release
      BUILD_LINK: shared

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: debug
      BUILD_LINK: static

    - BUILD_ADDRESS_MODEL: 64
      BUILD_VARIANT: release
      BUILD_LINK: static

matrix:
  fast_finish: true

build_script:
  - build/win/build.bat toolset=msvc link=%BUILD_LINK% boost=source boost-link=%BUILD_LINK% variant=%BUILD_VARIANT% address-model=%BUILD_ADDRESS_MODEL%
